name: Build Program
run-name: ${{ github.actor }} is building the program 🛠️
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/checkout@v2
      # - name: Check codestyle
      #   run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code
      - name: Build application
        run: make